spring.application.name=oauth-assignment
server.port=8080

# Google OAuth2 Credentials
spring.security.oauth2.client.registration.google.client-id= client id
spring.security.oauth2.client.registration.google.client-secret= Client Secret
spring.security.oauth2.client.registration.google.scope=profile,email

# SLF4J / Logback Logging Configuration (Assignment Requirement 2)
logging.level.root=INFO
logging.level.org.springframework.security=DEBUG
logging.level.com.data.oauth=INFO
logging.file.name=logs/app-security.log